version: '3'
services:
  web:
    image: server
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  nginx: # nginx 컨테이너
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge